job_finder:
    resource: "@JobFinderJobFinderBundle/Resources/config/routing/job.yml"
    prefix:   /job

job_finder_homepage:
    path:     /
    defaults: { _controller: "JobFinderJobFinderBundle:Job:index" }
